<?
/**
*	Simple XML parser
*	This file can be called via AJAX in order to generate a Table with the data recieved from the XML, which is generated by the Python script.
*	The python script itself can be put into a cronjob. In this case here, I'm executing it directly through PHP which COULD be unsafe on some server...
*	This script is provided as is and the author cannot be held responsible for any damage.
*
*	Author: Nickolas Simard
*	Original Idea: Nehpyrin
*	Website: http://www.nickolabs.com/
*	Last updated: December 11th, 2009
*
* 	Extra note: The author is bilingual, and code in two languages in some place... bear with it! :P
*/
require( 'includes/xmlLib.php' );
require( 'includes/function.php' );
$xmlurl = "http://www.nickolabs.com/hyperbol/servers.xml"; // Treated as remote

/* Exemple de Array 2 XML
$array = new ArrayToXML( $xml->getArray(), $xml->getReplaced(), $xml->getAttributes() );
print_r( $array->getXML() );*/

//Usage:	$xml = new XMLToArray( xmldata (string), ignorefields (array 1,2,3), replacefields(array OLD => NEW), show attributes?, convert to upper );
//$xml = new XMLToArray( 'http://www.slashdot.org/slashdot.xml', array(), array( 'story' => '_array_' ), true, false );
function load_xml()
{
	global $xmlurl, $xml, $array_xml, $arr_attributes, $arr_attributes_master, $updated, $players_online, $xml_age;
	$xml = new XMLToArray( $xmlurl, array(), array( 'server' => '_array_' ), TRUE, FALSE);
	$array_xml = $xml->getArray();
	$arr_attributes = $xml->getAttributes();
	// Récupère les attrib de "masterquery" (update timestamp et Players)
	$arr_attributes_master = $arr_attributes[0];
	$arr_attributes_master = $arr_attributes_master['serverlist'];
	$arr_attributes_master = $arr_attributes_master[0];
	// Récupère les attrib de chaque server pour le merge... + simplifie (root du array)
	$arr_attributes = $arr_attributes[1];
	$arr_attributes = $arr_attributes['server'];
	
	$updated = $arr_attributes_master['mktime'];
	$players_online = $arr_attributes_master['players'];
	$xml_age = mktime() - $updated;
}
//
// Load the XML and
// check if the data are fresh... if not, refresh them. Age is in Seconds
//
load_xml();
if ($xml_age >= 60)
{
	// Force Refresh the data
	$output = exec('python querymaster.py');
	// Load it again
	load_xml();
}

// Merge Manuel des deux arrays de valeurs (Les infos et les attributes)
$x = 0;
$array_result = array();
foreach ($arr_attributes as $server)
{
	// This server is not responding, so structure will differ
	if ($server['responding'] == 0)
	{
		// Add important parsing field...
		$server['version'] 		= '';
		$server['servername'] 	= '';
	}
	$array_result[] = $server;
	$x++;
}
// Vide les variables qui ne seront plus utilisé.
unset($server, $x, $arr_attributes, $array_xml, $arr_attributes_master, $xml, $xml_age);

// Array sorting... Default : Offline/Online, Name
// Note: Après qq test, les Offline était top list... ajout de "result" dans le sort.
// Le "vrai" Sorting est par nom... mais version et result passe quand même avant, puisque ce ne seront jamais des columns "sort_by"

// Warning: array_multisort() [function.array-multisort]: Array sizes are inconsistent in /home/nickolas/public_html/hyperbol/includes/function.php(55) : eval()'d code on line 1
$array_result = dynamic_multisort($array_result, array('version','responding','servername'), array('SORT_DESC','SORT_DESC','SORT_ASC'));

/*
OLD XML GENERATOR - Nephyryn
	[name] => House of Virtue - QC Server
    [version] => 1.08b
    [map] => a_Fission
    [gametype] => Deathmatch
    [currentplayers] => 
    [maxplayers] => 8
    [officialflavor] => 6
    [skill] => 4

NEW XML GENERATOR - Vek / Hyrkali
	[gametype] => Deathmatch
	[ip] => 76.168.185.136
	[mapname] => a_doommkii.hba
	[maxplayercount] => 8
	[playercount] => 0
	[port] => 12133
	[responding] => 1
	[servername] => Veks California DM
	[skill] => 4
	[version] => 1.08b
	[flavor] => 6
	
TIMED OUT / LOCALHOSTED SERVER
	[ip] => 77.68.136.165
	[port] => 12129
	[responding] => 0
	[flavor] => 0
	
*/?><p>Players online:
	<?=$players_online; ?>
	<br />
	&nbsp;</p>
<div id="background"></div>
<table class="server_list" width="960" cellpadding="8" cellspacing="0">
	<tr>
		<th>Status</th>
		<th>Name</th>
		<th>Map</th>
		<th>Gametype</th>
		<th>Players</th>
		<?php /*?>
		<th style="border-right:#FFFFFF solid 2px; border-bottom:#FFFFFF solid 2px;">Flavor</th><?php */?>
		<th style="border-right:0;">Skill</th>
	</tr>
	<?php
foreach ($array_result as $server)
{		
	// Generate the "5/16" player output
	$output_players = "";
	if ($server['playercount'] < 1)
	{
		$currentplayers = 0;
	}
	else
	{
		$currentplayers = $server['playercount'];		
	}
	$output_players = $currentplayers . "/" . $server['maxplayercount'];
	
	// 0 = default - not official server
	// 1 = IMF home server (objective mode)
	// 2 = REP home server (objective mode)
	// 3 = SYN home server (objective mode)
	// 4 = Arena (Elimination)
	// 5 = Team Arena (Team Elimination)
	// 6 = Bounty Arena (First to 500 bounty wins)
	// 7 = Training Arena (New players allowed in only)
	switch ($server['flavor'])
	{
		case 1:
			$flavor = "IMF home server";
		break;
		case 2:
			$flavor = "REP home server";
		break;
		case 3:
			$flavor = "SYN home server";
		break;
		case 4:
			$flavor = "Arena";
		break;
		case 5:
			$flavor = "Team Arena";
		break;
		case 6:
			$flavor = "Bounty Arena";
		break;
		case 7:
			$flavor = "Training Arena";
		break;
		default:
			$flavor = "Unofficial";
		break;
	}
	// Détecte la version du serveur
	// Current : 1.08b
	if ($server['version'] <> '1.08b' && $server['version'] <> '')
	{
		$server['responding'] = "version"; // Pour le switch du Status...
	}
	// Localhosted game
	else if ($server['version'] == '')
	{
		$server['servername'] = 'Locally hosted server (' . $flavor . ')';
		$server['responding'] = 'localhost';
	}
	
	// 0 - anyone can join
	// 1 - Training Servers - only very new players can join
	// 2 - Beginners Only
	// 3 - Novices Only
	// 4 - Anything above Novice (pro)
	// Mettre un code de couleur à barre...
	switch ($server['skill'])
	{
		case 1:
			$skill = "Training";
		break;
		case 2:
			$skill = "Beginner";
		break;
		case 3:
			$skill = "Novice";
		break;
		case 4:
			$skill = "Pro";
		break;
		default:
			$skill = "Free";
		break;
	}
	
	// Status
	// Image Led and Output details
	$img_alt_text = "";
	switch ($server['responding'])
	{
		case 1:
		case "success":
			$led_icon = "led_green.gif";
			$img_alt_text = "Online";
		break;
		case 0:
		case "timeout":
			$led_icon = "led_red.gif";
			$img_alt_text = "Timed Out";
			$output_players = "";	
			$skill = "";
			$server['name'] = "<em>Server is not responding.</em>";
		break;
		case "version":
			$led_icon = "led_yellow.gif";
			$img_alt_text = "Server is running a different version of Hyperbol (" . $server['version'] . ").";
		break;
		case 2:
		case "localhost":
			$led_icon = "led_grey.gif";
			$img_alt_text = "This game is locally hosted and cannot be pinged.";
		break;
		default:
			$led_icon = "led_grey.gif";
			$img_alt_text = "N/A";
			$output_players = "";	
			$skill = "";
		break;
	}
	// Map download Link
	$map = strtolower($server['mapname']);
	if (file_exists("maps/" . $map . ".hbc"))
	{
		$map = $map . " (<a href='maps/" . $map . ".hbc'>download</a>)";
	}
	
	// ID de TSHB: -applaunch 2720 
	// steam://run/2720+connect:" . $server['addr']
	// Ca boot le jeu, mais ca connecte pas, puisqu'il faut se connecter sur Starport une fois ingame... too bad.
	echo "<tr align='center'><td><img src='image/" . $led_icon . "' alt='" . $img_alt_text . "'  title='" . $img_alt_text . "' /></td><td>" . $server['servername'] . "</td><td>" . $map . "</td><td>" . $server['gametype'] . "</td><td>" . $output_players . "</td><td>" . $skill . "</td>";	//<td>" . $flavor . "</td>
	echo "</tr>";
}
unset($server);
	?>
</table>
<p class="last_update">List was last updated :
	<?=date("D F j, Y H:i:s", $updated); ?>
</p>
